apiVersion: apps/v1
kind: Deployment
namespace: mcapp
metadata:
  name: eks-mcapp-linux-deployment
  namespace: mcapp
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
        containers:
        - name: nginx
          image: sirfragalot/docker-demo:dcus
          ports:
          - name: http
            containerPort: 8080
          imagePullPolicy: IfNotPresent
        nodeSelector:
        kubernetes.io/os: linux